#spring:
#  application:
#    name: nacos-consumer
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 10.4.60.73:8848
#
#server:
#  port: 9091
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"